### ISSUE TITLE
有测过GPT-4V在定位上的能力吗

### ISSUE THREAD

**Issue by KainingYing** [albertwy/GPT-4V-Evaluation#1]
如题，请问你们有测过GPT-4V在在定位上的表现吗

**Comment by albertwy** [comment]
我们尝试让它生成一些坐标出来但是效果不太好。 最近的[SoM](https://arxiv.org/pdf/2310.11441.pdf)也发现这个问题。
>  For REC, we convert the masks into boxes for our method. When prompting GPT-4V to directly output the coordinates, we attain significantly poor performance (25.7).

我们没有报GPT-4V在定位的效果主要原因是觉得这样对比不是特别公平，我们不知道GPT-4V是否像通义千问用定位数据微调过，或者微调过，微调的形式具体是什么。
<img width="585" alt="image" src="https://github.com/albertwy/GPT-4V-Evaluation/assets/17995697/b062b108-2374-4021-b28a-25a370118958">
所以，对于这个任务需要一些额外处理解决比较好，比如SoM提出的Prompting技巧。

**Comment by KainingYing** [comment]
谢谢，我们确实也测试过，定位确实不行
